language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
matrix:
  include:
  - env: eslint
    sudo: false
    install:
      - nvm install 8
      - npm install
    script:
      - node ./node_modules/eslint/bin/eslint.js --ext .js src/jupyter_notebook_gist/static
sudo: false
cache: pip
install:
  - pip install tox codecov
script:
  - tox -v -e py
after_success:
  - codecov
allow_failures:
  - env: eslint
